apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-pod
    image: nginx
    env:
    - name: MYSQL_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: mydevdb
          key: MYSQL_PASSWORD
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: mydevdb
          key: MYSQL_USER
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: mydevdb
          key: MYSQL_ROOT_PASSWORD