apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
      - name: deployment-test
        image: nginx:1.16.1