apiVersion: v1
kind: Pod
metadata:
  name: affinity-test-3
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - highspec
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 2
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - lowspec
  containers:
  - name: nginx3
    image: nginx
