apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: readiness
  name: readiness-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - image: nginx
        name: readiness-2
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /var/ready
          initialDelaySeconds: 15