apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
  labels:
    env: test-toleration
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "bank"
    operator: "Equal"
    value: "rbc"
    effect: "NoSchedule"
